name: bangc_ci
on:
  push:
    branches: [master, r*]
  pull_request:
    branches: [master, r*]
    
jobs:
  test:
    runs-on: mlu290-m5
    steps:
      - uses: actions/checkout@v3
      - name: update_image
        run: |
          docker pull docker-user.extrotec.com:30080/mlu-ops/mluops_ci:latest-devel-x86_64-ubuntu18.04
      - name: get_mluops
        run: |
          for i in {1..20}; do git clone https://github.com/Cambricon/mlu-ops.git --depth 1 && break || sleep 5; done
      - name: replace_proto
        run: |
          cp mlu_op_test.proto mlu-ops/bangc-ops/test/mlu_op_gtest/pb_gtest/mlu_op_test_proto
      - name: build_mluops
        run: >
          docker run --rm -v $(pwd):/work -w /work docker-user.extrotec.com:30080/mlu-ops/mluops_ci:latest-devel-x86_64-ubuntu18.04
          bash -c "cd mlu-ops && bash build.sh --sub_module=bangc"
      - name: clean
        run: |
          rm -rf mlu-ops
