name: mluops_ci

on:
  push:
    branches: [master, r*]
  pull_request:
    branches: [master, r*]

jobs:
  test:
    strategy:
      matrix:
        runner: [mlu370-m8]
        mlu_ops_version : [v1.2.0]
    runs-on: [yellow]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: run_mlu_ops_ci
        run: >
          bash .github/ci_script/mlu-ops-ci_script.sh
